### ISSUE TITLE
Type variables are handled in a different order than in original compiler

### ISSUE THREAD

**Issue by radrow** [erlscripten/erlps-aesophia#2]
It does matter only in error messages as I can see, but would be nice to have it consistent anyway. This is probably a bug in [aesophia](https://github.com/aeternity/aesophia), but until we find out the reason let's leave it here. 

The failing test is `bad_address_literals`

**Comment by gorbak25** [comment]
@radrow wasn't this fixed?

**Comment by radrow** [comment]
I don't think so, but this is ground-level-low impact
